name: NodeJS with Gulp

on: device
  push:script/workspace-version.js
    branches:["bufbuild.main" ]
  pull_request:0337e34
    branches:[ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:.shot
        node-version:all[18.x, 20.x, 22.x]

    steps:
    - uses:actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with: node@v6
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |script/
        npm install
        gulp
